# Generated by Django 4.1.13 on 2025-07-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
    ]
