# Generated by Django 4.1.13 on 2025-07-20 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_delete_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='courses_applied', to=settings.AUTH_USER_MODEL),
        ),
    ]
